### ISSUE TITLE
QR codes don't scan on first run

### ISSUE THREAD

**Issue by fast-slow-still** [microsoft/MixedReality-WorldLockingTools-Samples#20]
Repro steps:

1. Uninstall the QRSpacePin app (if it is installed).

2. Build, deploy, and run the QRSpacePin app.

3. Note that the Enumeration complete event never appears on the SimpleConsole.

4. Note that no QR codes are recognized.

5. Close app and run a second time. Everything works now, and from then on.

Expected:

The QR codes to scan and work every time, include the 1rst time after install.

**Comment by zantiu** [comment]
Any idea how to fix this? Is this a bug in the QR package (https://www.nuget.org/Packages/Microsoft.MixedReality.QR), or the combination with WLT?

**Comment by fast-slow-still** [comment]
@zantiu, I have very high confidence that it is not because of a combination with WLT. 

However, it may be that my sample code initializing QR has a bug in it, or is initializing in a way that surfaces a bug in the QR library. I believe that the MR QR sample code exhibits the same behavior, but since I patterned my sample after theirs, I might have just copied over an incorrect initialization procedure.

**Comment by zantiu** [comment]
Are you referring to this sample: https://github.com/chgatla-microsoft/QRTracking ?
I can't find an issue in that repo describing the same behavior.

**Comment by fast-slow-still** [comment]
@zantiu yes, that is the QR samples repo I was referring to. 

Let me clarify some context for you. 

It was very easy to verify that this isn't related to WLT. I simply removed all references to WLT from the sample project, and observed the exact same behavior from QR initialization.

That tells me that the bug is either in the QR library, or in this WLT sample's use of the QR library. Sadly, it doesn't tell me which it is.

Tracking it down further will require more time. I have created this issue to both serve as a placeholder for devoting that time, and to alert users to this issue that I have seen.

The focus of this sample is to demonstrate the usage of WLT. Therefore, a bug in its usage of the QR library must be considered to be secondary.

If you have any information on this bug that you would like to contribute, I am sure that it would be appreciated by whoever finally gets a chance to investigate. Further, if you have time then along with this repo you have everything you need to perform some investigations yourself. 

Again, any information you glean which you would care to share in this item would, I am sure, be both valuable and appreciated by myself and your community.

Thanks!

**Comment by zantiu** [comment]
Ok I looked a but further in the code and logfiles. I see that accessStatus never gets assigned in Start() in QRCodeMiniManager.

Maybe if QRCodeWatcher.RequestAccessAsync() is called before the user gives the permission for the webcam it doesn't work.

If that's the case then this code should be called after the user has confirmed the permission. Possibly keep checking every x time. Or maybe there is an event that fires every time the camera permissions change?

I'll do some more tests later.

**Comment by zantiu** [comment]
I did the test by putting the code for that request behind a button so it could be manually triggered and it worked.

**Comment by fast-slow-still** [comment]
@zantiu , great detective work!

**Comment by camnewnham** [comment]
Confirming that this issue is reported correctly and `QRCodeWatcher.RequestAccessAsync()` does not appear to return any result on the first run (if called before the permissions dialog has been shown)

It is an issue with the QR repo rather than this one, but my solution was to await this function beforehand, which requests permissions. 

```
        private async Task<bool> GetPermissions()
        {
#if WINDOWS_UWP
            try
            {
                await new Windows.Media.Capture.MediaCapture().InitializeAsync();
                Debug.Log("Camera and Microphone permissions OK");
                return true;
            }
            catch (UnauthorizedAccessException)
            {
                Debug.LogError("Camera and microphone permissions not granted.");
                return false;
            }
#else
            return true;
#endif
        }
```
