### ISSUE TITLE
Move a QRCode/SpacePin in the physical world without altering the virtual world

### ISSUE THREAD

**Issue by Luckypon** [microsoft/MixedReality-WorldLockingTools-Samples#34]
Hello, I'm trying to move a QR code connected to a spacepin.
In my system, I dynamically add/remove spacepins when I scan different QR codes.

1. I scan QR code A (that is the origin, known in the database). Then I scan QR codes B and C and dynamically add them to my database. Then I place holograms in the world. Everything works fine.
2. Let's say I want to move QR Code C in the physical world (for X reasons) WITHOUT moving the virtual world.
I delete the space pin related to QR code C.

SpacePinOrientable spacePin is my spacePin.

```
spacePin.Reset()
alignSubtree.RemoveOwnedPin(spacePin)
Destroy(spacePin.gameObject)
```

I wait for two frames before allowing the hololens to scan again QR codes (not sure if it's necessary).

3. I move the QR code C in the physical world (without scanning it) e.g a few centimeters.
4. I try to scan it (and dynamically add it) again.

Result : there is a "bug", like if the qr code C was still in the memory and WLT try to adjust the previous virtual world to the new physical world (and it's not matching). My holograms position is now wrong.
To correct it, I need to delete it again (like step 2). If I scan it again, without moving the physical QR code, it works.

Is there a way to totally remove a Space pin from WLT ? or is there another issue, something I'm doing wrong ?

**Comment by Luckypon** [comment]
I update a previous git to reproduce the bug
https://github.com/Luckypon/SharingHolograms

**Comment by fast-slow-still** [comment]
In your description of steps, you leave out where you update the modeling position of the SpacePin. Could you add that in?

**Comment by Luckypon** [comment]
I call ResetModelingPose() when : 
- I create a new spacePin 

```
_spacePin = gameObject.AddComponent<SpacePinOrientable>();
_spacePin.Orienter = _myManager.MyOrienter;
_spacePin.ResetModelingPose();
```

- I update it when I load my database : 
```
_spacePin.transform.SetGlobalPose(GetCurrentGlobalPose());
_spacePin.ResetModelingPose();
```

- When I scan a new QR code (unknown to the database) : 

I create a new spacePin and place it.
I obtain the frozenPose with the coordinateSystem.
I wait for two frames
I calculate the lockedPose
If the lockedPose has changed or the space pin is inactive --> I call ResetModelingPoseAtOrigin() then set the FrozenPose()

```
 private void ResetModelingPoseAtOrigin()
    {
        Vector3 localPos = _spacePin.transform.localPosition;
        Quaternion localRot = _spacePin.transform.localRotation;
        Transform parent = transform;

        _spacePin.transform.SetParent(null);
        _spacePin.transform.position = localPos;
        _spacePin.transform.rotation = localRot;

        _spacePin.ResetModelingPose();

        _spacePin.transform.SetParent(parent);
        _spacePin.transform.localPosition = localPos;
        _spacePin.transform.localRotation = localRot;
    }
```

PS : I often wait for two frames because at the time it corrected some bugs of mine (seems like I needed to wait for the spacePin to initialize with Start() before setting its frozenPose).

**Comment by Luckypon** [comment]
I create a new spacePin and place it.
I obtain the frozenPose with the coordinateSystem.
I wait for two frames
I calculate the lockedPose
If the lockedPose has changed or the space pin is inactive --> I call ResetModelingPoseAtOrigin() then set the FrozenPose()

```
var markerData = GetMarkerDataByQrCode(qrCode);
currentMarker = CreateNewVirtualMarkerByScan(markerData);
currentMarker.UpdateByQRJustAdded(qrCode);

private MarkerData GetMarkerDataByQrCode(QRCode qrCode)
{
        _tmpCoordinateSystem.SpatialNodeId = qrCode.SpatialGraphNodeId;
        if (_tmpCoordinateSystem.ComputePose(out Pose spongyPose))
        {
            Pose frozenPose = WorldLockingManager.GetInstance().FrozenFromSpongy.Multiply(spongyPose);
            MyPositionMarkerHelper.SetGlobalPose(frozenPose);
            Pose localPose = MyPositionMarkerHelper.GetLocalPose();

            return new MarkerData(
                true,
                qrCode.Data,
                localPose.position,
                localPose.rotation,
                qrCode.PhysicalSideLength
                );

        }
        return null;
    }
```

**Comment by fast-slow-still** [comment]
I can't tell what the purpose of ResetModelingPoseAtOrigin is. Can you explain what the goal of the function is, and what each of the steps is trying to do?

**Comment by fast-slow-still** [comment]
Apologies, I have had a personal emergency come up, and won't be able to follow up on this for a few weeks. If I get a chance, I will post back any thoughts or relevant questions, but otherwise my ability to help you with this will be very limited. Best wishes.

**Comment by Luckypon** [comment]
I've written ResetModelingPoseAtOrigin() because simply doing spacePin.ResetModelingPose() wasn't working well for me.
I think it's because all of my space pins are in a sub space (like in QRSubScene.scene) that is not located at (0,0,0) after I've scanned a first QR code and aligned my virtual world to my physical world. 
That's why I change my spacePin's parent to null, call ResetModelingPose() and then revert my spacePin's parent.

Ok I understand ! Best wishes too.

**Comment by Luckypon** [comment]
So, after a few more tests, it seems that it was the QR code scan that is not working very well when I scan a QR code that I've moved in the physical world. 

I'll do a few more tests and post it here if I find a solution..

**Comment by Luckypon** [comment]
It was the QR code scan that was malfunctionning. 
To correct it, when I scan a new QR code (unknown from the database), I put a proxy spacePin on its location (I've not yet called SetFrozenPose() on it). Then this proxy space pin is updated every time my scan sent a new location.
The user need to click on a button when he finds it satisfying enoug to call SetFrozenPose() on this spacePin and add it to the database.
