### ISSUE TITLE
QRCodeSpacePins are not persistent with recent WLT versions

### ISSUE THREAD

**Issue by aleneum** [microsoft/MixedReality-WorldLockingTools-Samples#42]
I recently updated WLT and realized that SpacePins set with QR-Codes stopped being saved/loaded correctly. Whenever I restart 
the program running on my HoloLens2, the scene transformation is more or less reset. I could reproduce this behavior with the sample code as written below. I adjusted the scene slightly to only use two markers which I printed on a sheet of paper.
The scene is saved and restored as expected when using the WLT version included in the sample. However, when I update CoreEngine and Tools (as well as the NuGet package dependencies), the scene is either not stored or loaded correctly.

### Preparation

* Clone `https://github.com/microsoft/MixedReality-WorldLockingTools-Samples.git`
* Load `Advanced/QRSpacePins` with UnityEditor (2019.4.22f1)
* Load Scene `Scenes/QRSpacePins`
* Remove all markers except `QRCode_1` and `QRCode_2` from `HouseHold/BarnMarkers/Markers`
* Reset transform of `QRCode_1` and  `QRCode_2`
* Set position of `QRCode_1` to `{x: -0.0625, y:0, z: 0.2025}` and `QRCode_2` to `{x: -0.0625, y: 0, z: 0.0625}`
* Adjust `Size` of `QRSpacePinGroup` of `MarkerPinsRoot/Barn_MarkerPins`
* Enable `AutoLoad` and `AutoSave` in `WorldLocking/WorldLockingManager`

### This works

* Build, deploy and run project (on HL2)
* accept all the permission dialogs and restart the program
* look at printout of [wlt_markers.pdf](https://github.com/microsoft/MixedReality-WorldLockingTools-Samples/files/6229865/wlt_markers.pdf)
* markers should be detected and scene should be adjusted
* restart program
* scene transformation should be loaded (`AnchorGraphVisual` '1' hovering above printout)

### This does not 

* Download [WLT 1.32](https://github.com/microsoft/MixedReality-WorldLockingTools-Unity/releases/tag/v1.3.2) `CoreEngine` and `Tools`
* Drag packages to UnityEditor and import them
* Update NuGet packages `FrozenWorld` to `1.1.0`, `VCRTForwarders` to `140.1.0.7` and `QR` to `0.5.2112`
* delete previous build folder
* Build, deploy and run project (on HL2)
* accept all the permission dialogs and restart the program
* look at printout of [wlt_markers.pdf](https://github.com/microsoft/MixedReality-WorldLockingTools-Samples/files/6229865/wlt_markers.pdf)
* markers should be detected and scene should be adjusted
* restart program 
#### What I expected
* scene transformation should be loaded (`AnchorGraphVisual` '1' hovering above printout)
#### What happened instead
* `AnchorGraphVisual` '1' hovers close to (but not exactly at the same position as) 'SpongySpace' root.

**Comment by fast-slow-still** [comment]
Thanks for the very detailed bug report. I have been able to reproduce the issue. I've ruled out a couple of things, but haven't found the failure point yet.

I hope to narrow down the problem and fix it tomorrow. I'll update this issue as the situation clarifies.

Thanks again for the detailed writeup, that is extremely helpful!

**Comment by aleneum** [comment]
Just FYI, I tested the QRCodeSpacePins example again with the recent release and things work fine 👍

**Comment by fast-slow-still** [comment]
Fantastic, I appreciate you taking the time to post an update!
