### ISSUE TITLE
SpacePin Sample with Unity 2020.3.13f1

### ISSUE THREAD

**Issue by zauberwuerfel4711** [microsoft/MixedReality-WorldLockingTools-Samples#68]
I am trying to use WLT with classes from the SpacePin Example with the Unity version 2020.3.13f1 Personal. The problem is that in the class QRSpatialCoord in line 203 there is following code:
```
rootCoordinateSystem = System.Runtime.InteropServices.Marshal.GetObjectForIUnknown(
                    UnityEngine.XR.WSA.WorldManager.GetNativeISpatialCoordinateSystemPtr()
                ) as SpatialCoordinateSystem;
```
The build-in XR was removed from Unity (https://stackoverflow.com/questions/66314181/unityengine-xr-wsa-worldmanager-namespace-not-found-where-does-it-reside-now). On Stackoverflow I found this solution:
`spatialCoordinateSystem = SpatialLocator.GetDefault().CreateStationaryFrameOfReferenceAtCurrentLocation().CoordinateSystem;`
With that Unity can build and Visual Studio is able to deploy it to the Hololens 2 and I am able to start the app. However it works not perfect, it recognizes the QrCodes, but the positioning in the room is just strange. It seems to me that it has a offset, but I have no clue where it comes from.
![grafik](https://user-images.githubusercontent.com/55993759/126497423-e8dda1d2-b6bf-4df3-88c9-6c5edeb8159c.png)

So, fits the stackoverflow solution for this too or do I need a different solution?

**Comment by fast-slow-still** [comment]
Hi, sorry about the delay, but I've been out of the office.

The QR Code Sample has only been verified to Unity 2019.4 (LTS). See [the docs](https://microsoft.github.io/MixedReality-WorldLockingTools-Samples/Advanced/QRSpacePins/QRSpacePins.html#dependencies) for fully supported configuration.

I would like to update this sample to support Unity 2020 (thanks for your notes there, they will be helpful!), but it needs to be scheduled in with other maintenance and feature development. I'll post back to this issue when I have a better estimate what the scope of work is and when it will be available.

Thanks!

**Comment by fast-slow-still** [comment]
See also issue #65

**Comment by fast-slow-still** [comment]
I have a version running locally using an OpenXR extension. Barring any more immediate crisis, I hope to get it checked in tomorrow.

**Comment by fast-slow-still** [comment]
Note that this fix uses the Microsoft OpenXR plugin, NOT the Windows Mixed Reality XR Plugin.

So currently supported platforms are legacy VR for Unity 2019, and OpenXR XR Plugin for Unity2020+.
