### ISSUE TITLE
Samples fail to compile and run on device

### ISSUE THREAD

**Issue by SimonDarksideJ** [microsoft/MixedReality-WorldLockingTools-Samples#77]
In attempting to clone and setup the samples to run on device, the current samples repo has several issues:

* None of the samples have been updated to use the new Mixed Reality Feature tool method of deployment using UPM
* Attempting to update the samples to the latest version of the MRTK fails
* Attempting to update the samples to the latest version of the WLT fails

In short, the samples need a serious update and upgrade to the latest versions / patterns.

**Comment by fast-slow-still** [comment]
This is by design. The samples are standalone snapshots, including all dependencies. Whereas the main repo must be able to accept a wide range of versions of dependencies, the samples are intended to show a single working configuration. They are not intended to be redundant with the main repo as a source for installing WLT.

**Comment by fast-slow-still** [comment]
By the way, it sounds like the samples included in the main repo might be more what you are looking for. I would especially recommend the [WorldLockedPhysicsSample](https://microsoft.github.io/MixedReality-WorldLockingTools-Unity/DocGen/Documentation/HowTos/Samples/WorldLockedPhysicsSample.html) as a general intro, and the [SpacePins](https://microsoft.github.io/MixedReality-WorldLockingTools-Unity/DocGen/Documentation/HowTos/Samples/SpacePin.html) sample as an introduction to the space pin concept.

They are available through the MR FeatureTool, and compatible with a wide range of Unity and MRTK versions.

**Comment by SimonDarksideJ** [comment]
The sample I'm having issue with is the ASA sample, simply downloading it causes several errors and is not deployable:

* Complains about missing frozen engine
* Incompatible with current version of ASA (which also needs installing with the Feature tool) - granted this may have been resolved with the latest update, but unless the sample is also updated, this does not help
* Does not compile
* Publishing to device doesn't work.

**Comment by SimonDarksideJ** [comment]
P.S. it's fine saying this method is "by design" but then the samples documentation should reflect this in its writing, as all a user has to go on is the "setup guides for  WLT" and a one line paragraph in the sample itself.

The instructions for cloning and running the projects as is, including any additional steps to import external assets should be included.  In other words, someone trying to use the sample shouldn't have to go looking elsewhere to get the sample running.

P.S. Samples need updating and aligning with the main WLT repo.

**Comment by fast-slow-still** [comment]
https://microsoft.github.io/MixedReality-WorldLockingTools-Samples/Advanced/ASA/ASA.html

<img width="543" alt="image" src="https://user-images.githubusercontent.com/37700878/144233813-93ab57af-4cd4-46ee-80b1-4e3ca52509fc.png">

I would actually recommend the [ASA sample from the main repo](https://microsoft.github.io/MixedReality-WorldLockingTools-Unity/DocGen/Documentation/HowTos/WLT_ASA.html). However note that there are extra steps there, since WLT obviously can't ship with every package that every sample might use. All of the steps called out in the documentation are required unless explicitly labeled optional.

**Comment by SimonDarksideJ** [comment]
Taking in to account your notes above, I followed the instructions step by step, except it fails when you need to install the frozen engine, as the project has script errors due to the frozen engine not being available you are unable to install and actually use the "NuGet for Unity" because the scipts cannot compile because the Frozen Engine is missing.  Hence you cannot then use NuGet for Unity to install the Frozen engine.

* Open Project
* Observe Frozen Engine script errors
* Import Nuget for Unity
* Nuget for Unity cannot compile, thus no options to use it to import the frozen engine.
* Stuck.

A Catch 22

**Comment by fast-slow-still** [comment]
NuGet for Unity is deprecated since Unity 2019. Use the manual install instructions.
https://microsoft.github.io/MixedReality-WorldLockingTools-Unity/DocGen/Documentation/HowTos/InitialSetup.html#manual-frozen-world-engine-dll-installation

**Comment by SimonDarksideJ** [comment]
Again, then the docs and instructions should reflect this so a reader has a clear indication for how to get the sample up and running (sorry if that sounds passive-aggressive, it's not meant to), it's just trying to find a clear point to help improve the docs.

This method is simply adding unnecessary friction to get users up and running, surely as the Frozen Engine is also available through the Mixed Reality Feature tool, would it not be easier to provide it that way to avoid confusion?
