### ISSUE TITLE
No sample for WLT without depending on the MRTK

### ISSUE THREAD

**Issue by SimonDarksideJ** [microsoft/MixedReality-WorldLockingTools-Samples#78]
The documentation clearly states that the MRTK is optional for using the WLT, however, no example exists that does not depend on the MRTK.

There are also no tutorials for attempting to use the WLT without the MRTK, which makes if very difficult in using this for its intended purpose.

Simple use case:
* Using the WLT for a digital twin scenario
* Having a lifesize virtual model of a space
* Aligning and anchoring that virtual model to the physical space

**Comment by fast-slow-still** [comment]
https://microsoft.github.io/MixedReality-WorldLockingTools-Samples/Tutorial/01_Minimal/01_Minimal.html

**Comment by SimonDarksideJ** [comment]
Sure, that sample shows how to INSTALL the WLT without the MRTK.

However, that is where the tutorial ends, nothing to show:

* How to create pins
* How to align models to the pins
* How to store pins
* How to align models to the space

The docs simply don't go through enough details for these simple scenarios and there is no further reading with this sample.

**Comment by SimonDarksideJ** [comment]
The sample is also out of date since the recommended approach for installing the WLT is via the Mixed Reality Feature Tool

**Comment by fast-slow-still** [comment]
No, you miss the point of the sample. It doesn't just install WLT into a project, it uses WLT in its most basic form to world-lock the coordinate space.

More advanced samples which require UI use MRTK for the UX elements, which is the recommended approach. 

WLT doesn't provide UX itself. If you would prefer to provide your own UX, then you can start from scratch or use the samples built on MRTK for, well, for samples.

**Comment by SimonDarksideJ** [comment]
Wasn't bothered about UX, but rather the API calls and requests to operate a digital twin and add/remove reference points via code.
